### PR TITLE
Add bruno collections for API testing

### PR DESCRIPTION
**Pull request by rahulporuri**
Quick experiment setting up a bruno collect to API test fossunited.org

### CODE REVIEW

**Comment by rahulporuri** [comment]
@vasujain275 do you have any experience adding API testing?

**Comment by vasujain275** [comment]
@rahulporuri I have experience with bruno in the past, all my personal projects use bruno and git to manage api testing. Here is the repo where I manage all my collections - https://github.com/vasujain275/brunoCollections

**Comment by rahulporuri** [comment]
@vasujain275 would you be interested in helping us do API testing for the app. Should we manage the bruno collection in the same Git repository or should we use a different Git repository?

If you are interested in contributing to API testing, we can sit down for a short chat where we explore the existing APIs and work out a plan for slowly introducing API testing for the platform.

**Comment by vasujain275** [comment]
@rahulporuri Yes I think we should make a subdirectory in our repo itself. We can have a meet on the details for how to implement it.

**Pull request closed without merging**
