### PR TITLE
feat(dashboard): event cfp manage

### PR DESCRIPTION
**Pull request by harshtandiya**
## What type of PR is this? (check all applicable)
- [x] 🍕Feature
- [ ] ⚙️Chore
- [ ] 🐛Bug Fix
- [ ] 🎨Style
- [ ] 🧑‍💻Refactor
- [ ] 📕Documentation
- [ ] 🏎️Optimization

## Description
Ability to manage CFP for an organizer

## Screenshots
image
image
image
image
image

### CODE REVIEW

**Comment by NagariaHussain** [comment]
image

**Comment by NagariaHussain** [comment]
image

I don't think the second title is required

**Comment by NagariaHussain** [comment]
image

This can be styled like a number card.

**Comment by NagariaHussain** [comment]
image

😉


Also, let's move download button to the right.

**Review by NagariaHussain — CHANGES_REQUESTED** [review]
.

**Comment by harshtandiya** [comment]
> image
> 
> I don't think the second title is required

It may look a bit weird without it, thoughts?

image

**Comment by harshtandiya** [comment]
Thoughts?
image

**Pull request merged**
