### PR TITLE
feat: hackathon registration workflow

### PR DESCRIPTION
**Pull request by harshtandiya**
- Partner Project Initial Setup (needs additional info to be added)
- TipTap text editor component
- Hackathon registration workflow. 

## Demo Video

[Screencast from 2024-05-27 17-09-45.webm](https://github.com/fossunited/fossunited/assets/73123690/1a4dcd2f-45e4-4f37-acd0-bb11c001d28b)

### CODE REVIEW

**Comment by RiyaMathew-11** [comment]
The design is clean and neat!

1. I think project details can be a taken upon later:

- IMO Priority now is to get registrations and see how many folks go for local editions. 
- People tend to decide on projects later 
- Adding project creation workflow initially to registrations might lead them to register later as well. 

2. Team name formation shouldn't be mandated - as folks choose to hack individually too. 
    
@wisharya @ansharora28 please share your thoughts on this too. 

A workflow I suggest: 

1. General registration 

- Enter self-details - name, email, choice for remote or localhost
- Then choice to hack individually or as a team. 

Once this is done - registration should be complete

Later on: 

1. Add team members
2. Add project

**Comment by RiyaMathew-11** [comment]
A few changes I think need to be incorporated after the restructure of the Partner projects program

1. We wouldn't be listing the partner projects along with registration but on a separate page - I will set this page up.

2. We would only need to see if they are working on a partner project -   a check box would be ideal, and a tag `Partner Project` on the project page. 

3. For partner projects, they would need to submit ~~repo links instead of PR links~~. 

Edit: I got it wrong, it's the reverse. 

For partner projects, it's about contributions, so instead of repo links, they should submit PR links for evaluation.

cc: @harshtandiya

**Comment by ansharora28** [comment]
This is neat.

@RiyaMathew-11 I asked Harsh to add the project field, it is required. All the local editions are being organised by college communities and expected registrations from just inside the campus are 200+, while our cap is 70-120.

The organisers will be using the projects field as a filtration criteria to take in participants. 

> Adding project creation workflow initially to registrations might lead them to register later as well.

That's fine I think.

> Team name formation shouldn't be mandated - as folks choose to hack individually too.

:+1:

**Comment by ansharora28** [comment]
We can remove partner projects from the page.

Instead, the question can be framed as " What do you plan to work on?"

- Build your own project (take details)
- Contribute to an open source project (take details - this could be a normal oss project or a partner project, we don't need to have a registration workflow for partner projects)

**Comment by harshtandiya** [comment]
@ansharora28 partner projects as well as localhosts are toggle-able. I can re-word the options tho, your suggestions suit it better. I think project link should be mandated, with option to edit all info later if needed. 

@RiyaMathew-11  Partner Projects are still not clear imo. I am having difficulty understanding the way to integrate it with the registration or team creation right now. Maybe a more clear workflow would be better appreciated.

Also, even if people are hacking alone, let's have them create a team with only one member, ie. themselves. We can make them name their team after themselves if they wish. This is for the sake of workflow. Let's not customize something too much which may have a simple implementaton

**Comment by RiyaMathew-11** [comment]
> Contribute to an open source project (take details - this could be a normal oss project or a partner project, we don't need to have a registration workflow for partner projects)

Checking through the [structure](https://demo.hedgedoc.org/s/WdN2MeKLyc) of partner projects programme, folks will be assigned issues by 10 July - they would ideally be able to create projects after this window. 

1. Would it be okay for them to wait till then to register? @ansharora28 

2. Is there a date fixed by which local host participants need to be confirmed? 


In case of contributions in general (not just partner projects) PRs, not project repo links, form the base for evaluation - how do we make them submit the links while registering? 

- It could be handled by draft PR links, but I am unsure how much feasible it is to mandate it while registering. 

While restructuring the partner program, it was @rahulporuri's suggestion if I am not wrong : to see if participants can make this choice - to build/contribute later on - after registering. 

It made sense to me too - as those folks who don't get assigned issues from the program, can still choose to build something else. - how can we handle this case?

**Comment by RiyaMathew-11** [comment]
> Also, even if people are hacking alone, let's have them create a team with only one member, ie. themselves.

I think this is confusing UX. We have communicated it in forum and with case of previous editions, that people can hack alone or as a team. 

While saying this, and still mandating a team field, telling them to enter their own names for singular hackers, implies to a confusing practice for me, when thinking from participants' side. 

I might be wrong but @wisharya, @rahulporuri can also check on this and share thoughts perhaps ? If this is good to go, then we can go with it.

**Comment by RiyaMathew-11** [comment]
> I am having difficulty understanding the way to integrate it with the registration or team creation right now. Maybe a more clear workflow would be better appreciated.

I would like to take sometime for this. I will share this in a few hrs.

**Comment by ansharora28** [comment]
> Would it be okay for them to wait till then to register?

If we are going ahead with the workflow I suggested above, they can just register under the option "I will contribute to an oss project" - which could be a partner or an OSS project. I don't think anyone would wait to get an issue assigned to register. If they don't get it, they contribute to another project/build their own thing/do not participate. This field is just for us to somehow be able to select serious participants (or rather, filter out spam) for local editions IF we get a lot of registrations for a particular venue.  

> Is there a date fixed by which local host participants need to be confirmed?

Nothing at our end, organisers will do this at their discretion.

>  how do we make them submit the links while registering?

Why do we need PR links during registrations? That's a post event procedure anyway right?

> to see if participants can make this choice - to build/contribute later on - after registering.

Yeah. 

Again, to make it clear - I'm only suggesting to have that field (optional that too) just so we are able to filter out spam applications for local participants. It serves absolutely no other purpose in terms of evaluation etc. People are free to work on anything they want regardless of whatever they chose in the registration form.


> I think this is bad UX. 

Not really, it would be a solo team. Most online hackathon platforms I've used have this feature. 

Participating alone should not restrict you from having a cool team name :smile: 
It'll be teams competing against each other, rather than Person A competing against Team cool_name .

**Comment by RiyaMathew-11** [comment]
> Why do we need PR links during registrations?

I saw that GitHub repo link is included in the registration form. 

For contributions, it should be PR links ideally. 

Plus why I feel an 'isPartnerProject' checkbox is needed for those contributions that are for partner projects - is for identification purposes. 

To filter them from the list of all projects, finally and collate PR links etc if needed and provided to maintainers. 

It won't be possible unless there is a way to identify them. It could be included in the registration or post that.

**Comment by RiyaMathew-11** [comment]
> Not really, it would be a solo team. Most online hackathon platforms I've used have this feature.

> Participating alone should not restrict you from having a cool team name 😄
> It'll be teams competing against each other, rather than Person A competing against Team cool_name 

Sure if it works that way, it's great. 

I just had and raised a query from the UX perspective - considering how the FOSS Hack workflow has been modelled for the past 3 years - I had envisioned a different modelling.

There are edge cases to this too, but we cannot consider it all as well. 



> If they don't get it, they contribute to another project/build their own thing/do not participate.

I am sorry but then my query here is - is this selection field editable now or if not can it be made editable? Can they go back and revert or is it a one-time choice? 

Another query I have is - if the purpose is for filtering and spam reduction - then projects can be created later / soon after registration too ? The local hosts can see if the teams have created projects and check them in. 

This would make the registration process easier IMO. We could even send reminders to create projects etc in time.

**Comment by ansharora28** [comment]
> For contributions, it should be PR links ideally.

We need not ask them to submit contributions/PRs (draft or otherwise) just for registering for FOSSHack.

> Plus why I feel an 'isPartnerProject' checkbox is needed for those contributions that are for partner projects - is for identification purposes.

Okay, but -

> We wouldn't be listing the partner projects along with registration but on a separate page - I will set this page up.

Why bring the partner projects workflow inside the registration process if this is a separate program with a different webpage anyway? FOSSHack participants (registered) can just go to partner project page - Submit whatever details you require them to? 

The registration page can just have a link to partner project webpage wherein you can mention details and add a seperate form to submit PRs etc.?

> is this selection field editable now or if not can it be made editable? Can they go back and revert or is it a one-time choice?

Again,this field serves no purpose at all other than a way for organisers to look at what the person is planning to work on. We'll add this wording accordingly so participants don't feel obliged to make a decision while registering.

**Comment by RiyaMathew-11** [comment]
> Why bring the partner projects workflow inside the registration process if this is a separate program with a different webpage anyway? FOSSHack participants (registered) can just go to partner project page - Submit whatever details you require them to?

Partner project workflow isn't different from the normal way of project creation. 

This separate page is a listing page of partner projects with links to their issue boards and discussion threads. For participants to go through. 

1. The contributor proposes to work on the issue in that issue's thread, and if they get assigned - they have to create a project in our FOSS Hack platform like any other participant. 

2. And this project should be listed in the other [list of projects](https://archive.fossunited.org/fosshack/2023/projects) too. Check the case of [circuitverse contributions](https://archive.fossunited.org/fosshack/2023/project?project=CircuitVerse%20Improvements%20Project) which was done for a partner project last time
We don't need a separate workflow. 

3. The only add-on needed is a checkbox to mention if the project is a partner project - so that they have a partner project label - to identify. 

_This can be during registration or after if the details submitted by the participant are editable._ 

@harshtandiya let me know if this workflow if clearer now

> is this selection field editable now or if not can it be made editable? Can they go back and revert or is it a one-time choice?

@harshtandiya Please also confirm this part.

**Pull request merged**
