### PR TITLE
REFACTOR!: move all tests to `test` directory of `fossunited`

### LINKED ISSUE #658: FIX CI : Refactor tests as per latest frappe requirements
### Issue description

It seems like frappe has changed how tests are written/accessed in the framework. This is resulting in failed CI for this project.

To fix:

- Move all the tests inside the `/<app>/tests` directory along with the `__init__.py` file.

References:

- https://github.com/frappe/frappe/blob/cf0f0a6e5f657187f10fbc9215f17da8d5200453/frappe/tests/README.md
- https://github.com/frappe/frappe/tree/develop/frappe/tests

### PR DESCRIPTION
**Pull request by harshtandiya**
## What type of PR is this? (check all applicable)

- [x] 🐛Bug Fix
- [x] 🧑‍💻Refactor

## Description

Refactored the tests and moved all the tests files under the `test` directory in the `fossunited` app folder.
This change comes after Frappe updated their testing workflow and framework. Now it is required by the framework to place all your tests files under a single test folder.

References:
https://github.com/frappe/frappe/blob/develop/frappe/tests/README.md

## Related Issues & Docs
closes #658

### CODE REVIEW

**Review by blaggacao — CHANGES_REQUESTED** [review]
You actually should not need to do this. If after https://github.com/frappe/frappe/pull/28032 there continues to be an issue, please raise it on https://github.com/frappe/frappe/pull/28000 and I'll try to figure out a fix asap.

See also: https://github.com/fossunited/fossunited/issues/658#issuecomment-2401879179

**Comment by blaggacao** [comment]
```
class TestFOSSChapter(UnitTestCase):
    def setUp(self):
        chapter = frappe.get_doc(
            {
```
@RiyaMathew-11 if you depend on `get_doc` it's rather likely an integration test case.

Think of unit test cases ones that validate `def validate` or other `def mylifecyclemethod` with a lot of use of `unittest.{Mock,patch}`, etc.

I havn't looked in detail, just as a high level remark.

**Comment by blaggacao** [comment]
Just a headsup while you're at it, there's another fun cleanup incoming: https://github.com/frappe/frappe/pull/28060

:smile:

**Comment by RiyaMathew-11** [comment]
> Just a headsup while you're at it, there's another fun cleanup incoming: [frappe/frappe#28060](https://github.com/frappe/frappe/pull/28060)
> 
> 😄

Wow - but honestly, I am indeed liking the new testing add-ons: proper and clean logging of errors are really helpful

**Pull request closed without merging**
