### PR TITLE
fix(hackathon dashboard): filter not working in organiser dashboard and other minor fixes

### LINKED ISSUE #475: [BUG] Hackathons - Filters for requests aren't working in localhost dashboard
### Describe the bug

While changing status for requests in the filters of localhost dashbaord, the view isn't updated. 

On a refresh, it goes back to all requests. 
Screenshot 2024-07-17 at 12 40 36 PM

Add-on: The numbers of pending requests aren't updated too. 

Browser: Chrome, Arc

### PR DESCRIPTION
**Pull request by RiyaMathew-11**
## What type of PR is this? (check all applicable)
- [x] 🍕Feature
- [x] ⚙️Chore
- [x] 🐛Bug Fix

## Description

- [x] Fixed the filter functionality in hackathon organiser dashboard.
    - The actual implementation was based on clicks in the filter select menu , but the [click event](https://github.com/fossunited/fossunited/blob/ed4b52d1f6a565d3a3695b1e8c76b57023f4e14d/dashboard/src/components/localhost/AttendeeRequestList.vue#L47) wasn't getting registered in the browser. 
    - Updated it to respond to changes in the state of the filter instead of relying on click events. By watching for changes in the filter state, the rest of the actions can now respond appropriately to the selected filter.
- [x] Fixed - rejected proposals not rendered or updated in localhost organisers' dashboard.  
- [x] Added a case to handle empty states if there are no requests in a particular filter. 
- [x] Refactored the use of multiple operators to apply conditional styling for Filter states. 
   - Replaced it with selectorClasses defined in the `FILTERS` object. 
   - Makes it readable and easy to maintain.
   - Added a Rejected Requests in the filter options too.
- [x] Fixed some typos 

## Related Issues & Docs

- Closes #475 

## Checklist
- [x] I have read the [contribution guidelines]("./docs/CONTRIBUTING.md").
- [x] I have tested these changes locally.
- [x] I have updated the documentation (If applicable).
- [x] ~The code follows the project's coding standards.~
- [x] I have added/updated tests, if applicable.

## Screenshots/GIFs/Screen Recordings (if applicable)

filter-fix

## Additional context

Experimented with [Volar](https://blog.vuejs.org/posts/volar-a-new-beginning) formatter, which seemed to be mostly reccommended with Vue, and wanted to propose if we could use it along with Prettier for HTML files. 

If not, can revert the files back with Prettier formatting.

### CODE REVIEW

**Comment by harshtandiya** [comment]
I see a lot of unwanted formatting changes, which I don't think follow the prettier format.

**Comment by RiyaMathew-11** [comment]
> I see a lot of unwanted formatting changes, which I don't think follow the prettier format.

@harshtandiya 
It's the Vue formatter - [Volar](https://blog.vuejs.org/posts/volar-a-new-beginning) which is recommended mostly for formatting Vue files. I just tried it to see how it works and wanted to propose after if we could use it.

**Comment by harshtandiya** [comment]
@RiyaMathew-11 rest of the project is formatted using prettier. Let's stick to one formatting tool

**Comment by RiyaMathew-11** [comment]
> @RiyaMathew-11 rest of the project is formatted using prettier. Let's stick to one formatting tool

I haven't finalised this - tried it just to propose in draft PR. If we decide to use prettier and not go with it, I would format it with prettier before the PR is merged.

cc: @rahulporuri

**Review by harshtandiya — DISMISSED** [review]
let's change the format back to prettier

**Comment by RiyaMathew-11** [comment]
> let's change the format back to prettier

This is done with new commit.

Based on the discussion that we could decide after the PRs are merged, whether to use Volar after the configurations are figured out.

**Comment by NagariaHussain** [comment]
The changing of color of the select input is not a conventional pattern and looks very odd.

**Comment by RiyaMathew-11** [comment]
> The changing of color of the select input is not a conventional pattern and looks very odd.

Okay, I didn't change it as it was part of the original implementation. 
I will make it all uniform - with all gray bg. 

cc: @harshtandiya

**Review by rahulporuri — APPROVED** [review]

**Comment by rahulporuri** [comment]
> Okay, I didn't change it as it was part of the original implementation.
I will make it all uniform - with all gray bg.

it's a style choice. i'm okay either way

**Comment by RiyaMathew-11** [comment]
> > Okay, I didn't change it as it was part of the original implementation.
> > I will make it all uniform - with all gray bg.
> 
> it's a style choice. i'm okay either way

I just made it uniform - it looks better like that too. 
Screenshot 2024-07-18 at 8 29 23 PM

Shall I proceed to merge the PR @rahulporuri ?

**Comment by rahulporuri** [comment]
@RiyaMathew-11 still LGTM

**Pull request merged**
