### PR TITLE
Adding FOSS Profiles!

### PR DESCRIPTION
**Pull request by harshtandiya**
## What type of PR is this? (check all applicable)
- [x] 🍕Feature
- [x] ⚙️Chore
- [ ] 🐛Bug Fix
- [x] 🎨Style
- [ ] 🧑‍💻Refactor
- [ ] 📕Documentation
- [ ] 🏎️Optimization

## Description
FOSS Profiles web views and functionalities to be added in this PR.

- [x] FOSS Profiles Public View
- [x] FOSS Profile Edit
- [x] Sign Up and Login
- [x] Adding Experience to Profile
- [x] Adding Education History to Profiles
- [x] Adding Projects to Profile

## Checklist
- [x] I have read the [contribution guidelines]("./docs/CONTRIBUTING.md").
- [x] I have tested these changes locally.
- [ ] I have updated the documentation (If applicable).
- [x] The code follows the project's coding standards.
- [ ] I have added/updated tests, if applicable.

### FOSS Profile
image
image
image
image

### Edit Profile
image
image

[Screencast from 2024-01-30 13-00-53.webm](https://github.com/fossunited/fossunited/assets/73123690/9effa13e-c081-4b81-945b-817e1be1d891)

### CODE REVIEW

**Comment by NagariaHussain** [comment]
Do add screenshots / videos.

**Comment by NagariaHussain** [comment]
Also, bundle files / build assets should be gitignored 😬

**Comment by harshtandiya** [comment]
@NagariaHussain Added the screenshot and Video

Also, should i delete the bundle files here?

**Comment by NagariaHussain** [comment]
Yes

**Comment by harshtandiya** [comment]
@NagariaHussain Done

**Pull request merged**
